server:
  port: 8081
  servlet:
    context-path: /accounts

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    url: jdbc:mysql://${MYSQL_HOST:localhost}:53306/msa
    jpa:
      hibernate:
        ddl-auto: validate